Repository openshift/service-serving-cert-signer, pull requests merged in 2018-07, with the labels that each got.

#10 add simple config merging
  pkg/operator/merge.go
  pkg/operator/merge_test.go
  pkg/operator/sync_v310_00.go
Labels: size/L

#16 Bump to latest version of release build-images
  hack/build-images.sh
  hack/lib/test/junit.sh
  hack/lib/util/golang.sh
  hack/test-go.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-govet.sh
  hack/verify-imports.sh
  hack/verify-upstream-commits.sh
  tools/gotest2junit/gotest2junit.go
  tools/gotest2junit/pkg/api/junit.xsd
  tools/gotest2junit/pkg/api/string.go
  tools/gotest2junit/pkg/api/test_case.go
  tools/gotest2junit/pkg/api/test_suite.go
  tools/gotest2junit/pkg/api/types.go
  tools/gotest2junit/test/test_test.go
Labels: lgtm, size/XL

#15 update dockerfile for new kind of build
  Dockerfile
  Makefile
  hack/lib/constants.sh
  images/service-serving-cert-signer/.cccp.yml
  images/service-serving-cert-signer/Dockerfile
  images/service-serving-cert-signer/bin/.gitignore
Labels: size/M

#18 make some existing logic and files easier to read
  glide.lock
  pkg/operator/merge.go
  pkg/operator/operator.go
  pkg/operator/read.go
  pkg/operator/sync_all_v311_00.go
  pkg/operator/sync_apiservice_v311_00.go
  pkg/operator/sync_signer_v311_00.go
  pkg/operator/sync_v310_00.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger_test.go
Labels: lgtm, size/XL

#19 v1.11.1
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/entry_test.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks/test/test_test.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter_test.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus_test.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/text_formatter_test.go
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.proto
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/lease_manager_test.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/buffered/buffered.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/truncate/truncate.go
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/kube-aggregator/Godeps/Godeps.json
Labels: lgtm, size/XXL
