Repository openshift/service-serving-cert-signer, pull requests merged in 2018-10, with the labels that each got.

#28 adjust manifests
  manifests/0000_05_service-serving-cert-signer_00_roles.yaml
  manifests/0000_05_service-serving-cert-signer_01_namespace.yaml
  manifests/0000_05_service-serving-cert-signer_02_crd.yaml
  manifests/0000_05_service-serving-cert-signer_03_cm.yaml
  manifests/0000_05_service-serving-cert-signer_04_sa.yaml
  manifests/0000_05_service-serving-cert-signer_05_deploy.yaml
  manifests/0000_05_service-serving-cert-signer_06_config.yaml
  manifests/image-references
Labels: approved, lgtm, size/XS

#29 Remove Simo Sorce from OWNERS
  OWNERS
Labels: lgtm, size/XS

#30 adjust manifest runlevel to 09
  manifests/0000_09_service-serving-cert-signer_00_roles.yaml
  manifests/0000_09_service-serving-cert-signer_01_namespace.yaml
  manifests/0000_09_service-serving-cert-signer_02_crd.yaml
  manifests/0000_09_service-serving-cert-signer_03_cm.yaml
  manifests/0000_09_service-serving-cert-signer_04_sa.yaml
  manifests/0000_09_service-serving-cert-signer_05_deploy.yaml
  manifests/0000_09_service-serving-cert-signer_06_config.yaml
Labels: lgtm, size/XS

#32 target master nodes from installer
  bindata/v3.10.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v3.10.0/service-serving-cert-signer-controller/deployment.yaml
  manifests/0000_09_service-serving-cert-signer_05_deploy.yaml
  pkg/operator/v310_00_assets/bindata.go
Labels: lgtm, size/M

#31 Add ConfigMap injection controller
  bindata/v3.10.0/configmap-cabundle-controller/clusterrole.yaml
  bindata/v3.10.0/configmap-cabundle-controller/clusterrolebinding.yaml
  bindata/v3.10.0/configmap-cabundle-controller/cm.yaml
  bindata/v3.10.0/configmap-cabundle-controller/defaultconfig.yaml
  bindata/v3.10.0/configmap-cabundle-controller/deployment.yaml
  bindata/v3.10.0/configmap-cabundle-controller/ns.yaml
  bindata/v3.10.0/configmap-cabundle-controller/sa.yaml
  bindata/v3.10.0/configmap-cabundle-controller/signing-cabundle.yaml
  bindata/v3.10.0/configmap-cabundle-controller/svc.yaml
  cmd/service-serving-cert-signer/main.go
  pkg/cmd/configmapcabundle/cmd.go
  pkg/controller/configmapcainjector/configmap_injecting_controller.go
  pkg/controller/configmapcainjector/configmap_injecting_controller_test.go
  pkg/controller/configmapcainjector/starter.go
  pkg/operator/sync_all_v311_00.go
  pkg/operator/sync_configmapcabundle_v311_00.go
  pkg/operator/v310_00_assets/bindata.go
Labels: lgtm, size/XXL

#33 Add taint+toleration to configmap controller
  bindata/v3.10.0/configmap-cabundle-controller/deployment.yaml
Labels: lgtm, size/XS

#35 update README.md
  README.md
Labels: lgtm, size/L

#36 Add leader election
  bindata/v3.10.0/apiservice-cabundle-controller/clusterrole.yaml
  bindata/v3.10.0/configmap-cabundle-controller/clusterrole.yaml
  bindata/v3.10.0/service-serving-cert-signer-controller/clusterrole.yaml
  pkg/cmd/apiservicecabundle/cmd.go
  pkg/cmd/configmapcabundle/cmd.go
  pkg/cmd/servingcertsigner/cmd.go
  pkg/controller/apiservicecabundle/starter.go
  pkg/controller/configmapcainjector/starter.go
  pkg/controller/servingcert/starter.go
  pkg/operator/v310_00_assets/bindata.go
Labels: lgtm, size/L
