Repository openshift/service-serving-cert-signer, pull requests merged in 2018-11, with the labels that each got.

#47 Fix crash on nil configMap data
  pkg/controller/configmapcainjector/configmap_injecting_controller.go
Labels: lgtm, size/XS

#43 Add ClusterIP type to controller service
  bindata/v3.10.0/apiservice-cabundle-controller/svc.yaml
  bindata/v3.10.0/configmap-cabundle-controller/svc.yaml
  bindata/v3.10.0/service-serving-cert-signer-controller/svc.yaml
  pkg/operator/v310_00_assets/bindata.go
Labels: lgtm, size/XS

#42 Add initial e2e test harness
  Makefile
  test/e2e.sh
  test/e2e/e2e_test.go
Labels: lgtm, size/L

#53 Update OWNERS to auth team members
  OWNERS
Labels: lgtm, size/S

#56 Make e2e test compile again
  test/e2e/e2e_test.go
Labels: lgtm, size/XS

#55 Enhance generic controller logic
  pkg/boilerplate/controller/controller.go
  pkg/boilerplate/controller/filter.go
  pkg/boilerplate/controller/sync.go
  pkg/controller/api/api.go
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller.go
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller_test.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
  pkg/controller/configmapcainjector/starter/starter.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller_test.go
  pkg/controller/servingcert/controller/secret_updating_controller.go
  pkg/controller/servingcert/controller/secret_updating_controller_test.go
  pkg/controller/servingcert/starter/starter.go
Labels: lgtm, size/XL

#57 Add initial implementation of singleton operator
  pkg/boilerplate/controller/controller.go
  pkg/boilerplate/controller/filter.go
  pkg/boilerplate/controller/option.go
  pkg/boilerplate/controller/sync.go
  pkg/boilerplate/operator/operator.go
  pkg/boilerplate/operator/option.go
  pkg/boilerplate/operator/sync.go
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_updating_controller.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_all_v311_00.go
  pkg/operator/sync_apiservice_v311_00.go
  pkg/operator/sync_configmapcabundle_v311_00.go
  pkg/operator/sync_signer_v311_00.go
Labels: approved, lgtm, size/XL

#60 Add filter by name utility functions
  pkg/boilerplate/controller/filter.go
  pkg/boilerplate/operator/filter.go
Labels: lgtm, size/M

#54 Filter operator informer events
  pkg/controller/api/resourcenames.go
  pkg/operator/operator.go
Labels: lgtm, size/M
